produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }

presentation:
    path:     /presentation/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }

panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }

livraison:
    path:     /livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

validation:
    path:     /validation
    defaults: { _controller: EcommerceBundle:Panier:validation }

categorieProduits:
    path:    /categorie/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:categorie }